<?php 

/* @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */ /* ex: \Magento\Catalog\Pricing\Price\RegularPrice */ 
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */ 

$priceModel = $block->getPriceType('regular_price'); 
/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */ 
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */

$finalPriceModel = $block->getPriceType('final_price'); $idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : ''; $schema = ($block->getZone() == 'item_view') ? true : false; $fprice=($finalPriceModel->getAmount()->getValue()); $rprice=$priceModel->getAmount()->getValue(); $discount = 100 - round(($fprice / $rprice) * 100); ?>
<?php if ($block->hasSpecialPrice()) :?>
    
        <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [ 'display_label' => __('Special Price'), 'price_id' => $block->getPriceId('product-price-' . $idSuffix), 'price_type' => 'finalPrice', 'include_container' => true, 'schema' => $schema ]); ?>
    
    <?= $discount."% Discount";?>
    
        <?= /* @noEscape */ $block->renderAmount($priceModel->getAmount(), [ 'display_label' => __(' '), 'price_id' => $block->getPriceId('old-price-' . $idSuffix), 'price_type' => 'oldPrice', 'include_container' => true, 'skip_adjustments' => true ]); ?>
    
<?php else :?>
    <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [ 'price_id' => $block->getPriceId('product-price-' . $idSuffix), 'price_type' => 'finalPrice', 'include_container' => true, 'schema' => $schema ]); ?>
<?php endif; ?>
<?php if ($block->showMinimalPrice()) :?>
    <?php if ($block->getUseLinkForAsLowAs()) :?>
        
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        
    <?php else :?>
        
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        
    <?php endif?>
<?php endif; ?>